# Generated by Django 3.1.2 on 2020-12-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='stockAmount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
