# Generated by Django 3.1.2 on 2021-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_variant_stockamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
