# Generated by Django 3.1.2 on 2020-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201208_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='exp_date',
            field=models.IntegerField(),
        ),
    ]
