# Generated by Django 3.1.2 on 2021-01-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjson',
            name='track',
            field=models.CharField(choices=[('CD', 'Confirmed'), ('SD', 'Shipped'), ('OD', 'OutForDelivery'), ('DL', 'Delivered')], default='CD', max_length=2),
        ),
    ]
